---
all:
  vars:
    ansible_user: "{{ super_user | default('k8s-admin') }}"
    ansible_become: yes
    ansible_become_method: sudo
    ansible_become_user: root
    # SSH configuration
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30 -o ServerAliveInterval=60 -o ServerAliveCountMax=3"
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_retries: 3
    # Network configuration
    cluster_vip: "{{ cluster_vip }}"
    cluster_domain: "{{ cluster_domain }}"
    pod_network_cidr: "{{ pod_network_cidr | default('192.168.0.0/16') }}"
    service_cidr: "{{ service_cidr | default('10.96.0.0/12') }}"
    # Registry configuration
    registry_port: "{{ registry_port | default('5000') }}"
  hosts:
    master-node-1:
      ansible_host: "{{ host_1 }}"
      node_ip: "{{ host_1 }}"
    master-node-2:
      ansible_host: "{{ host_2 }}"
      node_ip: "{{ host_2 }}"
    master-node-3:
      ansible_host: "{{ host_3 }}"
      node_ip: "{{ host_3 }}"
    registry-server:
      ansible_host: "{{ host_registry }}"
      node_ip: "{{ host_registry }}"
  children:
    masters:
      hosts:
        master-node-1:
        master-node-2:
        master-node-3:
    haproxy:
      hosts:
        master-node-1:
    local_repo:
      hosts:
        master-node-1:
    registry:
      hosts:
        registry-server:
    k8s_cluster:
      children:
        masters