---
- name: Проверка существования пользователя
  user:
    name: "{{ k8s_user }}"
    state: present
    groups: wheel
    append: yes
    shell: /bin/bash

- name: Установка hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Добавление записей в /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    backup: yes
  when: inventory_hostname == "master-node-1"

- name: Отключение swap
  shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab

- name: Настройка timezone
  timezone:
    name: "{{ timezone }}"

- name: Проверка наличия офлайн-пакетов
  stat:
    path: "{{ k8s_home }}/k8s-offline/files/packages"
  register: offline_packages_dir
  ignore_errors: yes

- name: Установка базовых пакетов для ALT Linux из офлайн-источника с fallback на интернет
  block:
    - name: Установка всех пакетов из офлайн-директории
      shell: |
        # Создаем временный локальный репозиторий
        cd {{ k8s_home }}/k8s-offline/files/packages
        dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz

        # Добавляем в sources.list
        echo "deb [trusted=yes] file:{{ k8s_home }}/k8s-offline/files/packages ./" > /etc/apt/sources.list.d/local-offline.list

        # Обновляем и устанавливаем все доступные пакеты
        apt-get update
        apt-get install -y ./*
      args:
        executable: /bin/bash
      when:
        - offline_packages_dir is defined
        - offline_packages_dir.stat is defined
        - offline_packages_dir.stat.exists
      ignore_errors: yes

    - name: Получение списка установленных пакетов
      shell: |
        dpkg-query -W -f='${Package} ${Status}\n' | grep "install ok installed" | awk '{print $1}'
      register: installed_packages
      ignore_errors: yes

    - name: Определение отсутствующих пакетов
      set_fact:
        missing_packages: "{{ required_packages | difference(installed_packages.stdout_lines | default([])) }}"
      vars:
        required_packages:
          - curl
          - wget
          - gnupg2
          - apt-transport-https
          - ca-certificates
          - bridge-utils
          - ntp
          - ntpdate
          - which
          - sudo

    - name: Показать отсутствующие пакеты
      debug:
        msg: "Отсутствующие пакеты: {{ missing_packages }}"
      when: missing_packages | length > 0

    - name: Установка отсутствующих пакетов из интернета
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ missing_packages }}"
      when: missing_packages | length > 0
      ignore_errors: yes  # Игнорируем ошибки при установке из интернета
      register: internet_install
      failed_when: false  # Никогда не считать эту задачу проваленной

    - name: Показать результат установки из интернета
      debug:
        msg: "Результат установки пакета {{ item.item }}: {{ item.failed | default(false) }}"
      loop: "{{ internet_install.results | default([]) }}"
      loop_control:
        label: "{{ item.item }}"

  rescue:
    - name: Установка всех пакетов из интернета (fallback)
      debug:
        msg: "Офлайн-пакеты недоступны или произошла ошибка, устанавливаем все пакеты из интернета"

    - name: Установка пакетов из интернета
      package:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - wget
        - gnupg2
        - apt-transport-https
        - ca-certificates
        - bridge-utils
        - ntp
        - ntpdate
        - which
        - sudo
      ignore_errors: yes  # Игнорируем ошибки при установке из интернета
      register: fallback_install
      failed_when: false  # Никогда не считать эту задачу проваленной

    - name: Показать результат fallback установки
      debug:
        msg: "Fallback установка пакета {{ item.item }}: {{ item.failed | default(false) }}"
      loop: "{{ fallback_install.results | default([]) }}"
      loop_control:
        label: "{{ item.item }}"

- name: Настройка параметров ядра
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  loop:
    - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }
    - { name: net.bridge.bridge-nf-call-iptables, value: 1 }
    - { name: net.ipv4.ip_forward, value: 1 }
    - { name: fs.inotify.max_user_watches, value: 524288 }
    - { name: fs.inotify.max_user_instances, value: 512 }
  ignore_errors: yes
  failed_when: false

- name: Создание базовых директорий
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ k8s_user }}"
    group: "{{ k8s_group }}"
  loop:
    - "{{ k8s_home }}/.kube"
    - "{{ k8s_home }}/.local"
    - /etc/kubernetes
    - /etc/kubernetes/manifests
    - /var/lib/kubelet
    - /var/lib/etcd
    - /opt/cni/bin
    - "{{ offline_files_path }}"
    - "{{ packages_path }}"
    - "{{ images_path }}"

- name: Настройка прав для пользователя на системные директории
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  loop:
    - /etc/kubernetes
    - /var/lib/kubelet
    - /var/lib/etcd

- name: Перезагрузка системы (требуется для применения параметров ядра)
  reboot:
    msg: "Reboot triggered by Ansible for kernel parameters"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: need_restart | default(false) | bool