---
- name: Проверка существования пользователя
  user:
    name: "{{ k8s_user }}"
    state: present
    groups: wheel
    append: yes
    shell: /bin/bash

- name: Установка hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Добавление записей в /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    backup: yes
  when: inventory_hostname == "master-node-1"

- name: Отключение swap
  shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab

- name: Настройка timezone
  timezone:
    name: "{{ timezone }}"

- name: Создание локального репозитория из офлайн пакетов
  block:
    - name: Создание директории для локального репозитория
      file:
        path: /tmp/local-repo
        state: directory
        mode: 0755

    - name: Копирование пакетов для локального репозитория
      copy:
        src: "{{ k8s_home }}/k8s-offline/files/packages/"
        dest: /tmp/local-repo/
        mode: 0644
        remote_src: yes

    - name: Создание индекс файла для локального репозитория
      command: >
        dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
      args:
        chdir: /tmp/local-repo
      ignore_errors: yes

    - name: Добавление локального репозитория в sources.list
      lineinfile:
        path: /etc/apt/sources.list
        line: "deb [trusted=yes] file:/tmp/local-repo ./"
        state: present

    - name: Обновление кэша apt с локальным репозиторием
      apt:
        update_cache: yes
        cache_valid_time: 3600
  when: extraction_result is defined and extraction_result.stat.exists

- name: Установка базовых пакетов для ALT Linux
  block:
    - name: Попытка установки из локального репозитория
      package:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - wget
        - gnupg2
        - apt-transport-https
        - ca-certificates
        - bridge-utils
        - ntp
        - ntpdate
        - which
      register: local_install
      ignore_errors: yes
      when: extraction_result is defined and extraction_result.stat.exists

    - name: Получение списка неустановленных пакетов
      set_fact:
        failed_packages: "{{ local_install.results | selectattr('failed') | map(attribute='item') | list }}"
      when:
        - extraction_result is defined
        - extraction_result.stat.exists
        - local_install is defined

    - name: Установка отсутствующих пакетов из интернета
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ failed_packages | default([]) }}"
      when:
        - failed_packages | length > 0
        - extraction_result is defined
        - extraction_result.stat.exists

    - name: Установка всех пакетов из интернета (если локальный репозиторий недоступен)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - wget
        - gnupg2
        - apt-transport-https
        - ca-certificates
        - bridge-utils
        - ntp
        - ntpdate
        - which
      when: extraction_result is not defined or not extraction_result.stat.exists

- name: Настройка параметров ядра
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_set: yes
  loop:
    - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }
    - { name: net.bridge.bridge-nf-call-iptables, value: 1 }
    - { name: net.ipv4.ip_forward, value: 1 }
    - { name: fs.inotify.max_user_watches, value: 524288 }
    - { name: fs.inotify.max_user_instances, value: 512 }

- name: Создание базовых директорий
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ k8s_user }}"
    group: "{{ k8s_group }}"
  loop:
    - "{{ k8s_home }}/.kube"
    - "{{ k8s_home }}/.local"
    - /etc/kubernetes
    - /etc/kubernetes/manifests
    - /var/lib/kubelet
    - /var/lib/etcd
    - /opt/cni/bin
    - "{{ offline_files_path }}"
    - "{{ packages_path }}"
    - "{{ images_path }}"

- name: Настройка прав для пользователя на системные директории
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  loop:
    - /etc/kubernetes
    - /var/lib/kubelet
    - /var/lib/etcd

- name: Очистка локального репозитория
  file:
    path: /tmp/local-repo
    state: absent
  when: extraction_result is defined and extraction_result.stat.exists

- name: Удаление локального репозитория из sources.list
  lineinfile:
    path: /etc/apt/sources.list
    line: "deb [trusted=yes] file:/tmp/local-repo ./"
    state: absent
  when: extraction_result is defined and extraction_result.stat.exists

- name: Обновление кэша apt после удаления локального репозитория
  apt:
    update_cache: yes
  when: extraction_result is defined and extraction_result.stat.exists

- name: Перезагрузка системы (требуется для применения параметров ядра)
  reboot:
    msg: "Reboot triggered by Ansible for kernel parameters"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime